const { ANIMAL_ITEMS } = require('./animals');

const ITEMS = {
  Padlock: {
    id: 'Padlock',
    name: 'Padlock',
    emoji: '<:ITPadlock:1410243142640336977>',
    rarity: 'Common',
    value: 500,
    useable: true,
    type: 'Consumable',
    note: '',
    image: 'https://i.ibb.co/bjm9Mbr5/Padlock.png',
    price: 35000,
    sellPrice: null,
  },
  SeraphicHeart: {
    id: 'SeraphicHeart',
    name: 'Seraphic Heart',
    emoji: '<:ITSeraphicheart:1410243519372853401>',
    rarity: 'Rare',
    value: 2000,
    useable: false,
    type: 'Consumable',
    note: '',
    image: 'https://i.ibb.co/45pFNnY/Seraphic-Heart.png',
    price: 300000,
    sellPrice: null,
  },
  Landmine: {
    id: 'Landmine',
    name: 'Landmine',
    emoji: '<:ITLandmine:1410243453140336692>',
    rarity: 'Rare',
    value: 1500,
    useable: true,
    type: 'Consumable',
    note: '',
    image: 'https://i.ibb.co/239w692Y/Landmine.png',
    price: 200000,
    sellPrice: null,
  },
  WheatSeed: {
    id: 'WheatSeed',
    name: 'Wheat seed',
    emoji: '<:ITWheatseed:1410241406206873753>',
    rarity: 'Common',
    value: 350,
    useable: false,
    type: 'Material',
    note: '',
    image: 'https://i.ibb.co/hRpZsFyX/Wheat-seed-package.png',
    price: 10000,
    sellPrice: null,
  },
  HarvestScythe: {
    id: 'HarvestScythe',
    name: 'Harvest Scythe',
    emoji: '<:ITHarvestscythe:1410243487965777950>',
    rarity: 'Rare',
    value: 800,
    useable: false,
    type: 'Tool',
    note: '',
    image: 'https://i.ibb.co/vCjYnjPS/Harvest-scythe.png',
    price: 120000,
    sellPrice: null,
  },
  Sheaf: {
    id: 'Sheaf',
    name: 'Sheaf',
    emoji: '<:ITSheaf:1410243260689027172>',
    rarity: 'Rare',
    value: 5000,
    useable: false,
    type: 'Material',
    note: '',
    image: 'https://i.ibb.co/60mfbHqp/Wheat.png',
    price: 0,
    sellPrice: 5000,
  },
  WateringCan: {
    id: 'WateringCan',
    name: 'Watering Can',
    emoji: '<:ITWateringcan:1410243468634099723>',
    rarity: 'Common',
    value: 350,
    useable: false,
    type: 'Tool',
    note: '',
    image: 'https://i.ibb.co/vv65JBH8/Watering-Can.png',
    price: 70000,
    sellPrice: null,
  },
  DiamondBag: {
    id: 'DiamondBag',
    name: 'Diamond Bag',
    emoji: '<:ITDiamondbag:1409940957700292669>',
    rarity: 'Prismatic',
    value: 0,
    useable: true,
    type: 'Chest',
    note: 'Give 10k Diamonds',
    image: 'https://i.ibb.co/fYXHjr13/Bag-of-Diamond.png',
    price: 100,
    sellPrice: null,
  },
  DiamondCrate: {
    id: 'DiamondCrate',
    name: 'Diamond Crate',
    emoji: '<:ITDiamondcrate:1409940970287661096>',
    rarity: 'Prismatic',
    value: 0,
    useable: true,
    type: 'Chest',
    note: 'Give 135k Diamonds',
    image: 'https://i.ibb.co/5xLZZ25K/Crate-of-Diamond.png',
    price: 900,
    sellPrice: null,
  },
  DiamondChest: {
    id: 'DiamondChest',
    name: 'Diamond Chest',
    emoji: '<:ITDiamondcrate:1409940982853537832>',
    rarity: 'Prismatic',
    value: 0,
    useable: true,
    type: 'Chest',
    note: 'Give 980k Diamonds',
    image: 'https://i.ibb.co/4nJR1ZnC/Chest-of-Diamond.png',
    price: 4900,
    sellPrice: null,
  },
  BanHammer: {
    id: 'BanHammer',
    name: 'Ban Hammer',
    emoji: '<:ITBanhammer:1410315855233028258>',
    rarity: 'Secret',
    value: 0,
    useable: true,
    type: 'Weapon',
    note: 'Admin only item',
    image: '',
    price: 0,
    sellPrice: null,
  },
  HuntingRifleT1: {
    id: 'HuntingRifleT1',
    name: 'Hunting Rifle Tier 1',
    emoji: '<:ITRifle1:1410892503007105024>',
    rarity: 'Common',
    value: 200,
    useable: false,
    type: 'Gun',
    note: '',
    image: 'https://i.ibb.co/3mbdZLv3/rifle.png',
    price: 50000,
    sellPrice: null,
  },
  BulletBox: {
    id: 'BulletBox',
    name: 'Bullet box',
    emoji: '<:ITBulletbox:1410481932629971014>',
    rarity: 'Common',
    value: 300,
    useable: true,
    type: 'Consumable',
    note: 'A bullet box gives 6 bullets.',
    image: 'https://i.ibb.co/TM3NStHG/Bullet-Box.png',
    price: 30000,
    sellPrice: null,
  },
  Bullet: {
    id: 'Bullet',
    name: 'Bullet',
    emoji: '<:ITBullet:1410481944252252221>',
    rarity: 'Common',
    value: 50,
    useable: false,
    type: 'Material',
    note: '',
    image: '',
    price: 0,
    sellPrice: null,
  },
  ...ANIMAL_ITEMS,
};

module.exports = { ITEMS };
