const { ANIMAL_ITEMS } = require('./animals');
const XLSX = require('xlsx');

function loadDigItems() {
  const workbook = XLSX.readFile('Dig item data.xlsx');
  const sheet = workbook.Sheets[workbook.SheetNames[0]];
  const rows = XLSX.utils.sheet_to_json(sheet, { header: 1 });
  const items = [];
  for (let i = 1; i < rows.length; i++) {
    const row = rows[i];
    if (!row || !row[0]) continue;
    let id = String(row[0]).replace(/\s+/g, '');
    if (/arcs of resurgence/i.test(row[0])) id = 'ArcsOfResurgence';
    const types = [row[5], row[6], row[7]]
      .filter(Boolean)
      .map(t => String(t).trim())
      .map(t => t.charAt(0).toUpperCase() + t.slice(1).toLowerCase());
    items.push({
      id,
      name: row[0],
      emoji: row[8],
      rarity: row[1],
      value: Number(row[3]) || 0,
      useable: false,
      types,
      note: '',
      image: '',
      price: '',
      sellPrice: Number(row[4]) || null,
      chance: Number(row[2]) || 0,
    });
  }
  return items;
}

const DIG_ITEMS = loadDigItems();

const ITEMS = {
  Padlock: {
    id: 'Padlock',
    name: 'Padlock',
    emoji: '<:ITPadlock:1410243142640336977>',
    rarity: 'Common',
    value: 100,
    useable: true,
    types: ['Consumable', 'Tool'],
    note: '',
    image: 'https://i.ibb.co/bjm9Mbr5/Padlock.png',
    price: 35000,
    sellPrice: null,
  },
  SeraphicHeart: {
    id: 'SeraphicHeart',
    name: 'Seraphic Heart',
    emoji: '<:ITSeraphicheart:1410243519372853401>',
    rarity: 'Rare',
    value: 500,
    useable: false,
    types: ['Consumable', 'Collectible'],
    note: '',
    image: 'https://i.ibb.co/45pFNnY/Seraphic-Heart.png',
    price: 300000,
    sellPrice: null,
  },
  Landmine: {
    id: 'Landmine',
    name: 'Landmine',
    emoji: '<:ITLandmine:1410243453140336692>',
    rarity: 'Rare',
    value: 350,
    useable: true,
    types: ['Consumable', 'Tool'],
    note: '',
    image: 'https://i.ibb.co/239w692Y/Landmine.png',
    price: 200000,
    sellPrice: null,
  },
  AnimalDetector: {
    id: 'AnimalDetector',
    name: 'Animal Detector',
    emoji: '<:ITAnimalDetector:1423678926215188700>',
    rarity: 'Godly',
    value: 0,
    useable: true,
    types: ['Consumable', 'Tool'],
    note: '',
    image: 'https://i.ibb.co/ks5qVpB6/Animal-Detector.png',
    price: 15000000,
    sellPrice: null,
  },
  VerdantLures: {
    id: 'VerdantLures',
    name: 'Verdant Lures',
    emoji: '<:ITVerdantLure:1423868583896944771>',
    rarity: 'Mythical',
    value: 500,
    useable: false,
    types: ['Consumable', 'Tool'],
    note: 'Doubles rare animal odds in the Temperate Forest for 20 successful hunts.',
    image: 'https://i.ibb.co/FqkdH7jq/Verdant-Lure.png',
    price: 500000,
    sellPrice: null,
  },
  SunprideLures: {
    id: 'SunprideLures',
    name: 'Sunpride Lures',
    emoji: '<:ITSunprideLure:1423868570529431713>',
    rarity: 'Mythical',
    value: 500,
    useable: false,
    types: ['Consumable', 'Tool'],
    note: 'Doubles rare animal odds in the Savannah for 20 successful hunts.',
    image: 'https://i.ibb.co/jPhwHF3r/Sunpride-Lure.png',
    price: 500000,
    sellPrice: null,
  },
  MarshlightLures: {
    id: 'MarshlightLures',
    name: 'Marshlight Lures',
    emoji: '<:ITMarshlightLure:1423868599860465786>',
    rarity: 'Mythical',
    value: 500,
    useable: false,
    types: ['Consumable', 'Tool'],
    note: 'Doubles rare animal odds in the Swamp for 20 successful hunts.',
    image: 'https://i.ibb.co/Vcn0BbXN/Marshlight-Lure.png',
    price: 500000,
    sellPrice: null,
  },
  SnowglassLures: {
    id: 'SnowglassLures',
    name: 'Snowglass Lures',
    emoji: '<:ITSnowglassLure:1423868557057458266>',
    rarity: 'Mythical',
    value: 500,
    useable: false,
    types: ['Consumable', 'Tool'],
    note: 'Doubles rare animal odds in the Arctic Tundra for 20 successful hunts.',
    image: 'https://i.ibb.co/TB77BzTz/Snowglass-Lure.png',
    price: 500000,
    sellPrice: null,
  },
  XPSoda: {
    id: 'XPSoda',
    name: 'XP Soda',
    emoji: '<:ITXPSoda:1414252478257561701>',
    rarity: 'Godly',
    value: 800,
    useable: true,
    types: ['Consumable', 'Material'],
    note: '',
    image: 'https://i.ibb.co/wNSPTskT/XP-Soda.png',
    price: 1300000,
    sellPrice: null,
  },
  WhiteCabbageSeed: {
    id: 'WhiteCabbageSeed',
    name: 'White Cabbage seed package',
    emoji: '<:ITWhiteCabbageSeedPackage:1424391380980994058>',
    rarity: 'Epic',
    value: 400,
    useable: false,
    types: ['Consumable', 'Material'],
    note: 'Unlocked at Farm Mastery Lv.30',
    image: 'https://i.ibb.co/Pvc27CM1/White-Cabbage-seed-package.png',
    price: 250000,
    sellPrice: null,
  },
  WhiteCabbage: {
    id: 'WhiteCabbage',
    name: 'White Cabbage',
    emoji: '<:ITWhiteCabbage:1424393105679061133>',
    rarity: 'Epic',
    value: 500,
    useable: false,
    types: ['Sellable', 'Material'],
    note: '',
    image: 'https://i.ibb.co/5xBDQrZ7/Cabbage-6.png',
    price: null,
    sellPrice: 400000,
  },
  WheatSeed: {
    id: 'WheatSeed',
    name: 'Wheat seed',
    emoji: '<:ITWheatseed:1410241406206873753>',
    rarity: 'Common',
    value: 50,
    useable: false,
    types: ['Consumable', 'Material'],
    note: '',
    image: 'https://i.ibb.co/hRpZsFyX/Wheat-seed-package.png',
    price: 10000,
    sellPrice: null,
  },
  PotatoSeed: {
    id: 'PotatoSeed',
    name: 'Potato seed package',
    emoji: '<:ITPotatoseed:1413869045429571614>',
    rarity: 'Rare',
    value: 150,
    useable: false,
    types: ['Consumable', 'Material'],
    note: '',
    image: 'https://i.ibb.co/ywBxrJh/Potato-seed.png',
    price: 75000,
    sellPrice: null,
  },
  HarvestScythe: {
    id: 'HarvestScythe',
    name: 'Harvest Scythe',
    emoji: '<:ITHarvestscythe:1410243487965777950>',
    rarity: 'Rare',
    value: 500,
    useable: false,
    types: ['Equipment', 'Tool'],
    note: '',
    image: 'https://i.ibb.co/vCjYnjPS/Harvest-scythe.png',
    price: 120000,
    sellPrice: null,
    durability: 25,
  },
  Sheaf: {
    id: 'Sheaf',
    name: 'Sheaf',
    emoji: '<:ITSheaf:1410243260689027172>',
    rarity: 'Rare',
    value: 250,
    useable: false,
    types: ['Material', 'Sellable'],
    note: '',
    image: 'https://i.ibb.co/60mfbHqp/Wheat.png',
    price: 0,
    sellPrice: 5000,
  },
  Potato: {
    id: 'Potato',
    name: 'Potato',
    emoji: '<:ITPotato:1413869500046119005>',
    rarity: 'Rare',
    value: 50,
    useable: false,
    types: ['Sellable', 'Material'],
    note: '',
    image: '',
    price: null,
    sellPrice: 40000,
  },
  WateringCan: {
    id: 'WateringCan',
    name: 'Watering Can',
    emoji: '<:ITWateringcan:1410243468634099723>',
    rarity: 'Common',
    value: 150,
    useable: false,
    types: ['Tool', 'Equipment'],
    note: '',
    image: 'https://i.ibb.co/vv65JBH8/Watering-Can.png',
    price: 70000,
    sellPrice: null,
    durability: 10,
  },
  DiamondBag: {
    id: 'DiamondBag',
    name: 'Diamond Bag',
    emoji: '<:ITDiamondbag:1409940957700292669>',
    rarity: 'Prismatic',
    value: 7500,
    useable: true,
    types: ['Container', 'Consumable', 'Collectible'],
    note: 'Give 10k Diamonds',
    image: 'https://i.ibb.co/fYXHjr13/Bag-of-Diamond.png',
    price: 100,
    sellPrice: null,
  },
  DiamondCrate: {
    id: 'DiamondCrate',
    name: 'Diamond Crate',
    emoji: '<:ITDiamondcrate:1409940970287661096>',
    rarity: 'Prismatic',
    value: 8000,
    useable: true,
    types: ['Container', 'Consumable', 'Collectible'],
    note: 'Give 135k Diamonds',
    image: 'https://i.ibb.co/5xLZZ25K/Crate-of-Diamond.png',
    price: 900,
    sellPrice: null,
  },
  DiamondChest: {
    id: 'DiamondChest',
    name: 'Diamond Chest',
    emoji: '<:ITDiamondcrate:1409940982853537832>',
    rarity: 'Prismatic',
    value: 9000,
    useable: true,
    types: ['Container', 'Consumable', 'Collectible'],
    note: 'Give 980k Diamonds',
    image: 'https://i.ibb.co/4nJR1ZnC/Chest-of-Diamond.png',
    price: 4900,
    sellPrice: null,
  },
  BanHammer: {
    id: 'BanHammer',
    name: 'Ban Hammer',
    emoji: '<:ITBanhammer:1410315855233028258>',
    rarity: 'Secret',
    value: 0,
    useable: true,
    types: ['Tool', 'Collectible', 'Cosmetic', 'ADMIN'],
    note: 'Admin only item',
    image: '',
    price: 0,
    sellPrice: null,
  },
  HuntingRifleT1: {
    id: 'HuntingRifleT1',
    name: 'Hunting Rifle Tier 1',
    emoji: '<:ITRifle1:1410892503007105024>',
    rarity: 'Common',
    value: 200,
    useable: false,
    types: ['Equipment', 'Tool'],
    note: '',
    image: 'https://i.ibb.co/3mbdZLv3/rifle.png',
    price: 50000,
    sellPrice: null,
    durability: 50,
  },
  BulletBox: {
    id: 'BulletBox',
    name: 'Bullet box',
    emoji: '<:ITBulletbox:1410481932629971014>',
    rarity: 'Common',
    value: 100,
    useable: true,
    types: ['Container', 'Material', 'Consumable'],
    note: 'A bullet box gives 6 bullets.',
    image: 'https://i.ibb.co/TM3NStHG/Bullet-Box.png',
    price: 30000,
    sellPrice: null,
  },
  Shovel: {
    id: 'Shovel',
    name: 'Shovel',
    emoji: '<:ITShovel:1412067842303594567>',
    rarity: 'Common',
    value: 225,
    useable: true,
    types: ['Tool', 'Equipment'],
    note: '',
    image: 'https://i.ibb.co/PGDZzsG3/Shovel.png',
    price: 50000,
    sellPrice: null,
    durability: 50,
  },
  Bullet: {
    id: 'Bullet',
    name: 'Bullet',
    emoji: '<:ITBullet:1410481944252252221>',
    rarity: 'Common',
    value: 20,
    useable: false,
    types: ['Consumable', 'Material'],
    note: '',
    image: '',
    price: 0,
    sellPrice: null,
  },
  ...Object.fromEntries(DIG_ITEMS.map(it => [it.id, it])),
  ...ANIMAL_ITEMS,
};

module.exports = { ITEMS, DIG_ITEMS };
