import os
import inspect
from io import BytesIO
from typing import Any

import discord
from PIL import Image

WARNING_EMOJI = "<:warning:1404101025849147432> "
# Message flag enabling Discord's v2 component system
COMPONENTS_V2_FLAG = discord.MessageFlags._from_value(1 << 15)
CARD_SETTING_EMOJI = discord.PartialEmoji(name="Botgear", id=1403611995814629447)

# Global reference to the modal class, set during setup
CardSettingsModal = None


class CardSettingsView(discord.ui.View):
    """Discord UI View for level card settings with v2 component layout."""
    
    def __init__(
        self, color: tuple[int, int, int], background_url: str, owner_id: int
    ) -> None:
        super().__init__(timeout=None)
        self.color = color
        self.background_url = background_url
        self.owner_id = owner_id

    def to_components(self) -> list[dict[str, Any]]:
        """Return components using Discord's v2 container layout."""
        
        # Extract the button components generated by :class:`discord.ui.View`
        base_components = super().to_components()[0]["components"]
        accent_color = (self.color[0] << 16) + (self.color[1] << 8) + self.color[2]

        # Compose container children: button row, separator, and text label
        container_children = [
            {"type": 1, "components": base_components},
            {"type": 14, "divider": True, "spacing": 1},
            {"type": 10, "content": "Customize your card"},
        ]

        # Wrap the children in a container (type 17) with the accent colour
        container = {
            "type": 17,
            "accent_color": accent_color,
            "components": container_children,
        }

        # The root must be an Action Row (type 1) containing the container
        return [{"type": 1, "components": [container]}]

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        if interaction.user.id != self.owner_id:
            await interaction.response.send_message(
                f"{WARNING_EMOJI}You can't interact with this command.",
                ephemeral=True,
            )
            return False
        return True

    @discord.ui.button(
        label="Card Setting",
        style=discord.ButtonStyle.gray,
        emoji=CARD_SETTING_EMOJI,
    )
    async def card_setting(
        self, interaction: discord.Interaction, button: discord.ui.Button
    ) -> None:
        # Use the modal class that was set during setup
        if CardSettingsModal is None:
            await interaction.response.send_message(
                f"{WARNING_EMOJI}Card settings modal is not available.",
                ephemeral=True,
            )
            return
        
        modal = CardSettingsModal(self.color, self.background_url, interaction.message)
        await interaction.response.send_modal(modal)


async def send_level_card(
    user,
    send,
    user_stats,
    user_card_settings,
    save_data,
    xp_needed,
    DEFAULT_COLOR,
    DEFAULT_BACKGROUND,
    render_level_card,
    *,
    allow_ephemeral: bool = False,
):
    """Render and send a user's level card."""
    user_id = user.id
    settings = user_card_settings.setdefault(
        user_id, {"color": DEFAULT_COLOR, "background_url": DEFAULT_BACKGROUND}
    )
    stats = user_stats.setdefault(
        user_id, {"level": 1, "xp": 0, "total_xp": 0}
    )
    save_data()
    color = settings["color"]
    background_url = settings["background_url"]
    avatar_asset = user.display_avatar.with_size(256).with_static_format("png")
    avatar_bytes = await avatar_asset.read()
    avatar_image = Image.open(BytesIO(avatar_bytes)).convert("RGBA")
    try:
        path = render_level_card(
            username=user.name,
            nickname=getattr(user, "display_name", user.name),
            level=stats["level"],
            xp=stats["xp"],
            xp_total=xp_needed(stats["level"]),
            rank=0,
            prestige=0,
            total_xp=stats["total_xp"],
            avatar_image=avatar_image,
            background_url=background_url,
            bar_color=color,
            outfile=f"level_{user_id}.png",
        )
        file = discord.File(path, filename=f"level_{user_id}.png")
        # Include a blank description so component rows render within the embed
        # area when using Discord's v2 components.
        embed = discord.Embed(description="\u200b")
        embed.set_image(url=f"attachment://level_{user_id}.png")
        view = CardSettingsView(color, background_url, user_id)
        send_kwargs = {"embed": embed, "file": file, "view": view}
        if "flags" in inspect.signature(send).parameters:
            send_kwargs["flags"] = COMPONENTS_V2_FLAG
        await send(**send_kwargs)
    except ValueError:
        settings["background_url"] = DEFAULT_BACKGROUND
        save_data()
        path = render_level_card(
            username=user.name,
            nickname=getattr(user, "display_name", user.name),
            level=stats["level"],
            xp=stats["xp"],
            xp_total=xp_needed(stats["level"]),
            rank=0,
            prestige=0,
            total_xp=stats["total_xp"],
            avatar_image=avatar_image,
            background_url=DEFAULT_BACKGROUND,
            bar_color=color,
            outfile=f"level_{user_id}.png",
        )
        file = discord.File(path, filename=f"level_{user_id}.png")
        # Maintain spacing so the separator and button are visually attached to the
        # embed image when an invalid background is provided.
        embed = discord.Embed(description="\u200b")
        embed.set_image(url=f"attachment://level_{user_id}.png")
        view = CardSettingsView(color, DEFAULT_BACKGROUND, user_id)
        kwargs = {"ephemeral": True} if allow_ephemeral else {}
        send_kwargs = {
            "content": f"{WARNING_EMOJI}Background image invalid; using default.",
            "embed": embed,
            "file": file,
            "view": view,
            **kwargs,
        }
        if "flags" in inspect.signature(send).parameters:
            send_kwargs["flags"] = COMPONENTS_V2_FLAG
        await send(**send_kwargs)
    finally:
        try:
            os.remove(path)
        except OSError:
            pass


def setup(
    tree,
    user_stats,
    user_card_settings,
    save_data,
    xp_needed,
    DEFAULT_COLOR,
    DEFAULT_BACKGROUND,
    render_level_card,
    CardSettingsModal_class=None,  # New parameter for the modal class
    **__
):
    """Register the level command with the provided command tree."""
    
    # Set the global reference to the modal class
    global CardSettingsModal
    CardSettingsModal = CardSettingsModal_class

    @tree.command(name="level", description="Show your level card")
    async def level_command(interaction: discord.Interaction):
        await interaction.response.defer()
        await send_level_card(
            interaction.user,
            interaction.followup.send,
            user_stats,
            user_card_settings,
            save_data,
            xp_needed,
            DEFAULT_COLOR,
            DEFAULT_BACKGROUND,
            render_level_card,
            allow_ephemeral=True,
        )
