name: Notify Discord
on: [push, pull_request]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"content": "New commit pushed to ${{ github.repository }}"}' \
            "$DISCORD_WEBHOOK_URL"
